trigger:
  batch: false
  branches:
    include:
    - 'main'
  paths:
    include:
    - pipelines/COMPANY-PRODUCT-nuget.yml
    - src/**

pr:
  branches:
    include:
    - 'main'
  paths:
    include:
    - pipelines/COMPANY-PRODUCT-nuget.yml
    - src/**

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: RunCd
    type: boolean
    default: false
  - name: nugetService
    type: string 
    default: "COMPANY-nuget-001"
  - name: versionToReplace
    type: string
    default: "1.0.0"

variables:
  - name: buildConfiguration
    value: 'Release'
  - name: dotnetVersion
    value: '10.x'
  - name: scriptsPath
    value: '$(System.DefaultWorkingDirectory)/scripts/ci'
  - name: srcPath
    value: '$(System.DefaultWorkingDirectory)/src'
  - name: srcSolution
    value: 'COMPANY.PRODUCT.sln'
  - name: packageProject
    value: 'COMPANY.PRODUCT.csproj'
  - name: testProject
    value: 'COMPANY.PRODUCT.Tests.csproj'
  - name: nugetConfig
    value: '$(System.DefaultWorkingDirectory)/.nuget/NuGet.config'
  - name: packageOutput
    value: '$(Build.ArtifactStagingDirectory)/nupkg_output'
  - name: artifactName
    value: 'nuget-package'
  - name: versionMajor
    value: '1'
  - name: versionMinor
    value: '1'

stages:
  - stage: ci
    jobs:
      - job: build_test_pack
        steps:
          - task: PowerShell@2
            displayName: 'Get-Version.ps1'
            inputs:
              targetType: 'inline'
              script: |
                $json = & "$(scriptsPath)/Get-Version.ps1" -VersionToReplace "${{ parameters.versionToReplace }}" -Major $(versionMajor) -Minor $(versionMinor) -Patch $(Build.BuildId)
                $versionObj = $json | ConvertFrom-Json

                Write-Host "##vso[task.setvariable variable=semanticVersion]$($versionObj.SemanticVersion)"
                Write-Host "##vso[task.setvariable variable=fileVersion]$($versionObj.FileVersion)"
                Write-Host "##vso[task.setvariable variable=assemblyVersion]$($versionObj.AssemblyVersion)"
                Write-Host "##vso[task.setvariable variable=informationalVersion]$($versionObj.InformationalVersion)"

          - task: PowerShell@2
            displayName: 'Set-Version.ps1'
            inputs:
              filePath: '$(scriptsPath)/Set-Version.ps1'
              arguments: '-Path $(srcPath) -VersionToReplace ${{ parameters.versionToReplace }} -Major $(versionMajor) -Minor $(versionMinor) -Patch $(Build.BuildId)'
              workingDirectory: '$(scriptsPath)'

          - task: UseDotNet@2
            displayName: 'Use .NET SDK $(dotnetVersion)'
            inputs:
              packageType: 'sdk'
              version: '$(dotnetVersion)'
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: 'dotnet restore'
            inputs:
              command: 'restore'
              projects: '$(srcPath)/**/$(srcSolution)'
              feedsToUse: 'config'
              nugetConfigPath: '$(nugetConfig)'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              command: 'build'
              projects: '$(srcPath)/**/$(srcSolution)'
              arguments: '--configuration $(buildConfiguration) /p:Version=$(semanticVersion) /p:FileVersion=$(fileVersion) /p:AssemblyVersion=$(assemblyVersion) /p:InformationalVersion=$(informationalVersion)'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: 'test'
              projects: '$(srcPath)/**/$(testProject)'
              arguments: '--configuration $(buildConfiguration) --no-build'
              publishTestResults: true

          - task: DotNetCoreCLI@2
            displayName: 'dotnet pack'
            inputs:
              command: 'pack'
              packagesToPack: '$(srcPath)/**/$(packageProject)'
              nobuild: true
              versioningScheme: 'off'
              arguments: '--configuration $(buildConfiguration) --output $(packageOutput) /p:Version=$(semanticVersion) /p:FileVersion=$(fileVersion) /p:AssemblyVersion=$(assemblyVersion) /p:InformationalVersion=$(informationalVersion)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish NuGet package artifact'
            inputs:
              PathtoPublish: '$(packageOutput)'
              ArtifactName: '$(artifactName)'
              publishLocation: 'Container'

  - stage: cd
    dependsOn: ci
    condition: and(succeeded(), or(and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest')), eq(${{ parameters.RunCd }}, true)))
    jobs:
      - job: publish_nuget
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download NuGet package artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: '$(artifactName)'
              downloadPath: '$(Pipeline.Workspace)'

          - task: NuGetToolInstaller@1
            displayName: 'Install NuGet'
            inputs:
              versionSpec: '*'
              checkLatest: true

          - task: NuGetCommand@2
            displayName: 'Publish to NuGet.org'
            inputs:
              command: 'push'
              feedsToUse: 'select'
              nuGetFeedType: 'external'
              includeNuGetOrg: true
              publishFeedCredentials: '${{ parameters.nugetService }}'
              packagesToPush: '$(Pipeline.Workspace)/$(artifactName)/**/*.nupkg'