trigger:
  batch: true
  branches:
    include:
    - 'develop'
    - 'main'
  paths:
    include:
    - src/Core/*
    - src/Infrastructure/*
    - src/Specs/*
    - src/Presentation/Function/*

pr:
  branches:
    include:
    - 'develop'
    - 'main'

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: subscriptionService
    type: string 
    default: "AZURE_DEVOPS_SERVICE_CONNECTION_NAME"

  - name: funcSettings
    type: object
    default: 
      - name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
        value: '$(appiKey)'
        slotSetting: false
      - name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
        value: '$(appiConnection)'
        slotSetting: false        
      - name: 'AZURE_FUNCTIONS_ENVIRONMENT'
        value: '$(environmentApp)'
        slotSetting: false
      - name: 'FUNCTIONS_EXTENSION_VERSION'
        value: '~$(funcVersion)'
        slotSetting: false
      - name: 'FUNCTIONS_WORKER_RUNTIME'
        value: '$(funcRuntime)'
        slotSetting: false
      - name: 'AzureWebJobs.<FUNCTION_NAME>.Disabled'
        value: 'false'
        slotSetting: false
      - name: 'MyFunction.TimerSchedule'
        value: '0 */5 * * * *'
        slotSetting: false

variables:
  - template: ../variables/ci-common.yml
  - name: versionMajor
    value: '1'
  - name: versionMinor
    value: '1'

stages:
  - stage: build
    jobs:
      - job: build_src
        steps:
          - task: UseDotNet@2
            displayName: 'use .net $(dotnetVersion)'
            inputs:
              packageType: 'sdk'
              version: '$(dotnetVersion)'
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: 'dotnet restore'
            inputs:
              command: 'restore'
              projects: |
                $(srcPath)/**/$(apiProject)
              feedsToUse: config
              nugetConfigPath: $(nugetConfig)

          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              command: 'build'
              projects: |
                $(srcPath)/**/$(apiProject)
              arguments: '--configuration $(buildConfiguration)'


      - job: test_unit
        dependsOn: build_src
        steps:
          - task: UseDotNet@2
            displayName: 'use .net $(dotnetVersion)'
            inputs:
              packageType: 'sdk'
              version: '$(dotnetVersion)'
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: 'dotnet restore'
            inputs:
              command: 'restore'
              projects: |
                $(srcPath)/**/*.csproj
              feedsToUse: config
              nugetConfigPath: $(nugetConfig)

          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: test
              projects: |
                $(unitPath)/**/$(unitProject)
              arguments: ''
            env:
              $(appcsEnvironmentVariable): $(appcsConnection)
              AZURE_STORAGE_CONNECTION: ''
              ASPNETCORE_ENVIRONMENT: $(environmentApp)
              AZURE_FUNCTIONS_ENVIRONMENT: $(environmentApp)

      - job: build_func
        dependsOn: test_unit
        steps:
          - task: DeleteFiles@1
            inputs:
              SourceFolder: '$(tempPath)'
              Contents: '**/*'
              RemoveDotFiles: true

          - task: UseDotNet@2
            displayName: 'use .net $(dotnetVersion)'
            inputs:
              packageType: 'sdk'
              version: '$(dotnetVersion)'
              includePreviewVersions: true

          - task: PowerShell@2
            displayName: 'Get-Version.ps1'
            inputs:
              targetType: 'inline'
              script: |
                $json = & "$(scriptsPath)/Get-Version.ps1" -VersionToReplace "1.0.0" -Major $(versionMajor) -Minor $(versionMinor) -Patch $(Build.BuildId)
                $versionObj = $json | ConvertFrom-Json

                Write-Host "##vso[task.setvariable variable=semanticVersion]$($versionObj.SemanticVersion)"
                Write-Host "##vso[task.setvariable variable=fileVersion]$($versionObj.FileVersion)"
                Write-Host "##vso[task.setvariable variable=assemblyVersion]$($versionObj.AssemblyVersion)"
                Write-Host "##vso[task.setvariable variable=informationalVersion]$($versionObj.InformationalVersion)"

          - task: PowerShell@2
            displayName: 'Set-Version.ps1'
            inputs:
              filePath: '$(scriptsPath)/Set-Version.ps1'
              arguments: '-Path $(funcPath) -VersionToReplace 1.0.0 -Major $(versionMajor) -Minor $(versionMinor) -Patch $(Build.BuildId)'
              workingDirectory: '$(scriptsPath)'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet restore'
            inputs:
              command: 'restore'
              projects: |
                $(funcPath)/**/*.csproj
              feedsToUse: config
              nugetConfigPath: $(nugetConfig)

          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              command: 'build'
              projects: |
                $(funcPath)/**/*.csproj
              arguments: '--output $(tempPath) --configuration $(buildConfiguration) /p:Version=$(semanticVersion) /p:FileVersion=$(fileVersion) /p:AssemblyVersion=$(assemblyVersion) /p:InformationalVersion=$(informationalVersion)'

          - task: ArchiveFiles@2
            displayName: 'Archive $(archiveFileFunc)'
            inputs:
              rootFolderOrFile: '$(tempPath)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(artifactsPath)/$(archiveFileFunc)'
              replaceExistingArchive: true

          - task: DeleteFiles@1
            inputs:
              SourceFolder: '$(tempPath)'
              Contents: '**/*'
              RemoveDotFiles: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
              pathToPublish: '$(artifactsPath)'
              artifactName: drop

  - stage: development
    dependsOn: build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/main')))
    variables:
      - template: ../variables/cd-development.yml

    jobs:
      - job: settings_func
        steps:
          - ${{ each appSetting in parameters.funcSettings }}:
            - task: AzureAppServiceSettings@1
              displayName: 'set_appsettings ${{ appSetting.name }}'
              inputs:
                azureSubscription: ${{ parameters.subscriptionService }}
                appName: '$(funcName)'
                appSettings: |
                  [
                    {
                      "name": "${{ appSetting.name }}",
                      "value": "${{ appSetting.value }}",
                      "slotSetting": "${{ appSetting.slotSetting }}"
                    }
                  ]
                slotName: ${{ parameters.slotName }}

      - job: deploy_func
        dependsOn: settings_func
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(artifactsPath)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploying $(funcName)'
            inputs:
              ConnectionType: 'AzureRM'
              ConnectedServiceName: ${{ parameters.subscriptionService }}
              subscriptionName: '$(subscriptionId)'
              appType: 'webApp'
              WebAppName: '$(funcName)'
              RemoveAdditionalFilesFlag: true
              packageForLinux: '$(artifactsPath)/**/$(archiveFileFunc)'
 
  - stage: production
    dependsOn: development
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))
    variables:
      - template: ../variables/cd-production.yml

    jobs:
      - job: deploy_approval
        pool: server
        timeoutInMinutes: 4320
        steps:
        - task: ManualValidation@0
          inputs:
           notifyUsers: $(deployApprovers)
           instructions: "Team: $(System.TeamProject)\r\nRepo: $(Build.Repository.Name)\r\nRequested by: $(Build.RequestedFor)\r\nBuild: $(Build.BuildNumber)\r\nUrl: $(Build.BuildUri)\r\nA new deployment has been requested. Please approve or reject the deployment."
           onTimeout: reject

      - job: settings_func
        dependsOn: deploy_approval
        steps:
          - ${{ each appSetting in parameters.funcSettings }}:
            - task: AzureAppServiceSettings@1
              displayName: 'set_appsettings ${{ appSetting.name }}'
              inputs:
                azureSubscription: ${{ parameters.subscriptionService }}
                appName: '$(funcName)'
                appSettings: |
                  [
                    {
                      "name": "${{ appSetting.name }}",
                      "value": "${{ appSetting.value }}",
                      "slotSetting": "${{ appSetting.slotSetting }}"
                    }
                  ]
                slotName: ${{ parameters.slotName }}

      - job: deploy_func
        dependsOn: settings_func
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(artifactsPath)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploying $(funcName)'
            inputs:
              ConnectionType: 'AzureRM'
              ConnectedServiceName: ${{ parameters.subscriptionService }}
              subscriptionName: '$(subscriptionId)'
              appType: 'webApp'
              WebAppName: '$(funcName)'
              RemoveAdditionalFilesFlag: true
              packageForLinux: '$(artifactsPath)/**/$(archiveFileFunc)'