variables:
  - name: rgEnvironment
    value: 'Production'
  - name: rgName  
    value: 'rg-PRODUCT-prod-001'
  - name: rgLocation
    value: 'westus2'
  - name: rgSharedName
    value: 'rg-SHARED-prod-001'
  - name: rgSharedLocation
    value: 'westus2'
  - name: kvName
    value: 'kv-PRODUCT-prod-001'
  - name: serviceConnectionIdentityObjectId
    value: ''
  - name: deployApprovers
    value: 'approver.email@goodtocode.com;'