variables:
  - group: COMPANY-rg-PRODUCT-prod
  - template: common.yml  
  - name: rgEnvironment
    value: 'Production'
  - name: rgName
    value: 'COMPANY-rg-PRODUCT-prod-001'
  - name: rgLocation
    value: 'West US 2'
  - name: 'appiName'
    value: 'appi-PRODUCT-prod-001'
  - name: 'cogName'
    value: 'cog-PRODUCT-prod-001'
  - name: cogsku
    value: 'S0'
  - name: cogtextName
    value: 'cogtext-PRODUCT-prod-225'
  - name: cogtextSku
    value: 'S'
  - name: 'funcNameFree'
    value: 'func-PRODUCT-free-prod-001'
  - name: 'funcNamePaid'
    value: 'func-PRODUCT-paid-prod-001'
  - name: 'funcNamePremium'
    value: 'func-PRODUCT-prem-prod-001'
  - name: 'kvName'
    value: 'kv-PRODUCT-prod-001'
  - name: 'logicName'
    value: 'logic-PRODUCT-NAME-prod-001'
  - name: 'nugetFeeds'
    value: 'select'
  - name: 'nugetType'
    value: 'external'
  - name: stName
    value: 'stPRODUCTprod001'
  - name: 'stblobcnName'
    value: 'stblobcn-PRODUCT-prod-001'
  - name: 'stblobcnNameLower'
    value: "$[lower(replace(variables['stblobcnName'], '-', ''))]"
  - name: 'teamscnName'
    value: 'teamscn-PRODUCT-prod-001'
  - name: 'teamscnNameLower'
    value: "$[lower(replace(variables['teamscnName'], '-', ''))]"
  - name: workName
    value: 'work-PRODUCT-prod-001'